name: Build new and modified HTML pages
on:
  push:
    branches: [ main ]
    paths:
      - pages/*.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - run: wget https://ebookipedia.github.io/java/BuildPage.jar
      - run: java -jar BuildPage.jar
