name: Build HTML pages
on:
  push:
    branches: [ main ]
    paths:
      - pages/*.html
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - run: java -version
      #- run: java -cp java HelloWorldApp
